db={
    'python_anywhere':{
        'host':'viswa.mysql.pythonanywhere-services.com',
        'user':'viswa',
        'password':'Missyou2!',
        'db':'viswa$default',
        'port':'0'},
    'local':{
        'host':'localhost',
        'user':'root',
        'password':'',
        'db':'test_db',
        'port':'0'
        }}